spring.application.name=previsoes-service
server.port=8084

spring.datasource.url=jdbc:postgresql://localhost:5432/ru_custos?currentSchema=previsoes
spring.datasource.username=postgres
spring.datasource.password=252107

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=previsoes

ru-custos.jwt.secret=troque-este-segredo-em-producao-precisa-ter-pelo-menos-32-bytes
