spring.datasource.url=jdbc:postgresql://postgres:5432/ru_custos?currentSchema=saldo
spring.datasource.password=${DB_PASSWORD}
ru-custos.jwt.secret=${JWT_SECRET}
ru-custos.servicos.contratos-url=http://contratos-service:8082
ru-custos.servicos.previsoes-url=http://previsoes-service:8084
ru-custos.servicos.siop-url=http://siop-service:8085
