spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?currentSchema=saldo&sslmode=require
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
ru-custos.jwt.secret=${JWT_SECRET}
ru-custos.servicos.contratos-url=https://${CONTRATOS_SERVICE_HOST}.onrender.com
ru-custos.servicos.previsoes-url=https://${PREVISOES_SERVICE_HOST}.onrender.com
ru-custos.servicos.siop-url=https://${SIOP_SERVICE_HOST}.onrender.com
